export type Category = 'Production' | 'Hackathon' | 'Internal';

export interface Project {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  challenge: string;
  approach: string;
  solution: string;
  results: string[];
  tags: string[];
  category: Category;
  role: string;
  timeline: string;
  liveUrl?: string;
  repoUrl?: string;
  featured: boolean;
  order: number;
}

export const projects: Project[] = [
  {
    slug: 'agent-code-of-conduct',
    title: 'Agent Code of Conduct',
    tagline: 'Production-Grade Governance Framework for AI Agent Infrastructure',
    description: 'An open-source framework for governing AI agent infrastructure at scale — defining roles, hierarchy, chain of command, ethics, absolute prohibitions, enforcement discipline, command responsibility for sub-agents, defense-in-depth security architecture, and scaling provisions from 4 agents to 100+.',
    challenge: 'As AI agent deployments grow from a handful to hundreds, the rules governing a small team must become the rules governing an organization. No existing framework addresses agent governance with the rigor needed for production environments — covering not just behavior, but hierarchy, accountability, discipline, and security layering.',
    approach: 'Designed a 13-section framework covering: dual entity structure (human org directs, agent infra fulfills), 6 role categories with cross-prohibitions, 4-tier hierarchy, 7 core ethics, 10 absolute prohibitions with zero tolerance, 4-level enforcement (Blue/Yellow/Red/Black), command responsibility doctrine, 6-layer defense-in-depth security, data governance with regulatory compliance gates, and scaling provisions for populations from 10 to 100+ agents.',
    solution: 'Organizations adopt the framework and customize it to their structure. Every agent must acknowledge the Code of Conduct upon activation. The command responsibility doctrine ensures parent agents are fully accountable for sub-agent actions — delegation is not absolution. Sentinel agents bypass the chain of command for security incidents.',
    results: [
      '13-section framework covering identity, roles, hierarchy, ethics, rules, enforcement, lifecycle, collaboration, security, data governance, scaling, and acknowledgment',
      '6-layer defense-in-depth architecture (Identity → Pre-Action → Runtime → Infrastructure → Audit → Adversarial)',
      'Command responsibility doctrine — parent agents accountable for all sub-agent actions',
      '4-level enforcement system with escalation and post-incident review',
      'MIT licensed — free to adopt, adapt, and distribute',
    ],
    tags: ['AI Agents', 'Governance', 'Security', 'Compliance', 'Open Source', 'Framework'],
    category: 'Production',
    role: 'Architect & Author',
    timeline: 'May 2026',
    repoUrl: 'https://github.com/FranklinIV94/agent-code-of-conduct',
    featured: true,
    order: -1,
  },
  {
    slug: 'showroom-automation-1',
    title: 'Showroom Automation',
    tagline: 'Premium E-Commerce & Product Showcase Platform',
    description: 'A premium e-commerce and product showcase platform for retail showrooms — pitch black aesthetic with restrained gold accents, product display, admin dashboard, and CRM automation. Deployed on Vercel with Supabase backend, designed for multi-state sales tax compliance.',
    challenge: 'A premium home goods retailer needed a digital presence matching their artisanal brand — not a generic Shopify template. The site needed to feel like a speakeasy, not a strip mall, while handling real e-commerce operations including multi-state sales tax, inventory, and customer relationship management.',
    approach: 'Designed the "Artisanal Speakeasy" aesthetic: pitch black (#0a0a0a), restrained gold accents, minimalist typography. Built with React + Vite for speed, Supabase for backend, Vercel for deployment. Architected a full Supabase schema covering products, variants, images, customers, orders, sales tax entries, nexus thresholds, and CRM events.',
    solution: 'Live deployment with the Artisanal Speakeasy aesthetic fully implemented. Backend architecture designed for multi-state sales tax compliance (3-phase rollout), CRM upsell automation (6 customer segments, 5 automated flows), and inventory management. Active retainer.',
    results: [
      'Live deployment with Artisanal Speakeasy aesthetic — pitch black + gold',
      'Full Supabase schema: products, variants, orders, sales tax, CRM events',
      'Multi-state sales tax architecture with nexus threshold tracking',
      'CRM automation design: 6 segments, 5 automated flows',
      'Active retainer client',
    ],
    tags: ['React', 'Vite', 'Supabase', 'Vercel', 'E-Commerce', 'TypeScript', 'Tailwind'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    liveUrl: 'https://vita-showroom.vercel.app',
    featured: true,
    order: 0.5,
  },
  {
    slug: 'medical-practice-1',
    title: 'Medical Practice Platform',
    tagline: 'HIPAA-Ready Patient Portal for Medical Practices',
    description: 'A Next.js 14 SSR patient portal with Supabase Auth (4-role RBAC), HIPAA-compliant architecture design, and AWS migration planning. Built for a Florida medical practice. Resellable to any healthcare provider needing a compliant patient portal.',
    challenge: 'Healthcare practices need patient portals that handle PHI, but the compliance overhead is enormous. Every hosting provider, database, and auth system in the PHI path requires a signed BAA. Most small practices can\'t afford enterprise HIPAA add-ons.',
    approach: 'Built a Next.js 14 SSR app with Supabase Auth supporting 4 roles (patient/staff/provider/admin) via JWT custom claims. Designed AWS migration plan that cuts hosting costs by 90%. Authored a full compliance decision framework covering PHI vs PII classification, BAA triggers, and hosting compliance matrices.',
    solution: 'Portal architecture is complete with RBAC, session timeout design, audit log foundation, and patient identity verification. AWS migration decision report authored with phased cutover (hosting first, data plane second). Comprehensive HIPAA compliance gap analysis with 5 remaining items before go-live.',
    results: [
      'Next.js 14 SSR with 4-role Supabase Auth (patient/staff/provider/admin)',
      'AWS migration plan: 90% cost reduction from enterprise hosting',
      'HIPAA compliance gap analysis with 5 items remaining',
      'BAA compliance framework for PHI workloads',
      'Pre-production — awaiting hosting decision',
    ],
    tags: ['Next.js', 'Supabase', 'HIPAA', 'AWS', 'Healthcare', 'TypeScript'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    featured: true,
    order: 0.6,
  },
  {
    slug: 'peo-automation-1',
    title: 'PEO Automation Platform',
    tagline: 'White-Label HR Workflow Automation for Professional Employer Organizations',
    description: 'A white-label HR workflow automation platform for Professional Employer Organizations — replacing fragmented manual packets with a unified system for employee onboarding, 9+ form types, multi-state W-4 support, admin workspace, team management, and full audit logging. Deployed on AWS (S3 + CloudFront + Lambda + Supabase).',
    challenge: 'PEOs managing HR paperwork across multiple client companies face constant, fragmented onboarding workflows. Manual packets, disconnected forms, no centralized tracking, and manual follow-ups on every form cost hours per week.',
    approach: 'Built a full-stack platform with tokenized form links per employee, a multi-step onboarding wizard, Supabase backend, and a real-time admin dashboard. Migrated from Vercel to AWS for cost savings and BAA compliance readiness.',
    solution: 'Admins generate unique form links per employee, send via email, and track submission status in real time. Employees complete forms on any device. Federal and state W-4 PDFs are pre-filled with employee data and merged into a downloadable package. Full audit logging with CSV/PDF export and date range filtering.',
    results: [
      'Full employee onboarding flow with 7-step wizard + 9+ form types',
      'Federal W-4 + 40+ state W-4 PDFs with AcroForm pre-fill via pdf-lib',
      'Real-time admin dashboard with team management and audit logging',
      'AWS deployment: S3 + CloudFront + Lambda + API Gateway ($7-15/mo)',
      'Tokenized iPad workflow for in-office tablet use',
      'SSN never in URLs — all PII handled server-side via Supabase',
      'Audit log export: CSV + PDF with date range filtering',
    ],
    tags: ['React', 'Supabase', 'AWS', 'Lambda', 'CloudFront', 'pdf-lib', 'Resend', 'HR Tech', 'PEO', 'TypeScript'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'April–May 2026',
    liveUrl: 'https://www.mypeocoforms.com',
    repoUrl: 'https://github.com/FranklinIV94/peo-automation-1',
    featured: true,
    order: 0,
  },
  {
    slug: 'all-lines-auto-crm',
    title: 'All Lines Auto CRM',
    tagline: 'Auto Body, Repair & Dealership Management',
    description: 'A custom CRM and inventory management system for auto body, repair shops, and auto dealerships — managing vehicle records, work orders, parts inventory, and customer communications in one platform.',
    challenge: 'Auto body, repair, and dealership operations required tracking vehicles through the repair lifecycle, managing parts inventory, handling work orders, and maintaining client communications — with no unified system to manage it all.',
    approach: 'Built a Next.js CRM with vehicle profiles, work order management, parts inventory tracking, and customer communication logs — integrated with shop workflows for seamless operations.',
    solution: 'Staff manage all vehicle and customer interactions from a unified dashboard — work orders, parts availability, repair status, and communication history in one place.',
    results: [
      'Vehicle management with full repair lifecycle tracking',
      'Work order management and parts inventory',
      'Customer communication history',
      'Private deployment for shop operations',
    ],
    tags: ['Next.js', 'CRM', 'Auto', 'PostgreSQL', 'TypeScript'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'April 2026',
    featured: true,
    order: 1,
  },
  {
    slug: 'prospyr-inc',
    title: 'Prospyr Inc',
    tagline: 'AI-Powered Business Operations Platform',
    description: 'A multi-agent AI system for All Lines Business Solutions — four specialized agents (Prospyr, Northstar, Southstar, Zo) with orchestration, persistent memory, OSINT enrichment, cold outreach, and client-facing portals to run the business autonomously.',
    challenge: 'Business operations at ALBS required coordinating multiple AI agents, multiple communication channels, and multiple clients — without a unified system to manage it all.',
    approach: 'Built a multi-agent platform with specialized agents (Prospyr Prime, Northstar, Southstar, Zo) connected via OpenClaw, with persistent memory via Obsidian, client portals via Next.js/Supabase, and real-time dashboards via SSE.',
    solution: 'Agents handle client onboarding, security monitoring, email, and business operations 24/7. The Prospyr Control Center dashboard provides a unified command interface. Clients self-serve via the ALBS onboarding portal.',
    results: [
      'Four-agent team running 24/7 across Oracle VPS, Northstar hardware, and Office Paled server',
      'ALBS client portal live at onboarding.simplifyingbusinesses.com',
      'Prospyr dashboard deployed at prospyr-dashboard.vercel.app',
      'Persistent memory system with Obsidian vault integration',
      'Overnight agents: research, competitive intel, knowledge maintenance, daily metrics',
      'OSINT enrichment pipeline: Apollo + Sherlock + GhostTrack wired into portal',
      'Cold outreach agent: personalized emails to new leads via Microsoft Graph API',
    ],
    tags: ['AI Agents', 'Multi-Agent', 'Next.js', 'TypeScript', 'Obsidian', 'Vercel', 'Supabase'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'March 2026',
    repoUrl: 'https://github.com/FranklinIV94/prospyr-inc',
    featured: true,
    order: 2,
  },
  {
    slug: 'ap-agent',
    title: 'AP Agent',
    tagline: 'Autonomous Accounts Payable on Kite Chain',
    description: 'An AI agent that executes business vendor payments autonomously — natural language instruction to on-chain settlement with zero human signatures mid-task.',
    challenge: 'Business accounts payable is a $1.2T market dominated by manual, error-prone workflows. Every business pays vendors, yet AI-native AP automation barely exists.',
    approach: 'Built a full-stack Next.js application with a natural language instruction parser, Kite AA SDK integration, and EIP-3009 gasless stablecoin transfers. The agent handles vendor discovery, Session creation via Agent Passport, payment signing, and on-chain settlement.',
    solution: 'User submits: "Subscribe to email verification API for $29/mo." The agent parses the instruction, creates a scoped budget session, signs an EIP-3009 gasless transfer, and settles the transaction on Kite Chain — with full on-chain attestation via Kite Scan.',
    results: [
      'Full E2E autonomous execution — zero human signatures',
      'EIP-3009 gasless transfers — no gas tokens required',
      'On-chain settlement with public audit trail',
      'Live demo deployed to Vercel',
    ],
    tags: ['AI Agents', 'Kite AI', 'Blockchain', 'Next.js', 'TypeScript', 'EIP-3009'],
    category: 'Hackathon',
    role: 'Sole Architect & Developer',
    timeline: 'March 2026',
    liveUrl: 'https://hackathon-kite.vercel.app',
    repoUrl: 'https://github.com/FranklinIV94/hackathon-2026',
    featured: true,
    order: 3,
  },
  {
    slug: 'albs-portal',
    title: 'ALBS Client Onboarding Platform',
    tagline: 'End-to-End Client Lifecycle Automation',
    description: 'A complete client lifecycle automation platform for All Lines Business Solutions — from first web form submission through onboarding, scheduling, and portal access. Built to replace manual data entry with end-to-end automation: intake forms, CRM pipeline, self-service booking with dual Outlook calendar sync, and client portals.',
    challenge: 'ALBS was managing client intake manually — intake form submissions went to email, someone manually entered leads, scheduling happened over email/phone, and there was no pipeline visibility. Leads were being lost between intake and onboarding.',
    approach: 'Built four systems working together: (1) Smart intake form with webhook-driven lead creation, (2) Admin CRM with kanban pipeline and bulk actions, (3) Client booking scheduler with dual Microsoft Graph calendar write, (4) Client onboarding wizard and portal with Stripe billing.',
    solution: 'When a prospect submits the intake form, a webhook automatically creates a CRM lead and sends a personalized onboarding email in under 5 seconds. Clients self-schedule appointments — which simultaneously write to both Franklin\'s and Nadesha\'s Outlook calendars. Admins get a full kanban pipeline with drag-and-drop stage progression, bulk actions, and real-time booking notifications.',
    results: [
      'Intake-to-lead in under 5 seconds — zero manual entry',
      'OSINT enrichment pipeline: Apollo (B2B intelligence) + Sherlock (400+ social profiles) + GhostTrack (phone validation, carrier, geolocation)',
      'Cold outreach agent: personalized emails to new leads from industry playbooks, sent via Microsoft Graph API',
      'Dual Microsoft Graph calendar write: Franklin + Nadesha Outlook simultaneously',
      'Admin receives booking notification email with client details and Zoom setup prompt',
      '7-column kanban pipeline with stage metrics and drag-and-drop progression',
      'Bulk actions: multi-select status change, service assignment, CSV export',
      'Quick add lead with automatic onboarding email dispatch',
    ],
    tags: ['Next.js', 'Microsoft Graph API', 'Supabase', 'Prisma', 'Resend', 'Stripe', 'TypeScript', 'Vercel'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'March–May 2026',
    liveUrl: 'https://onboarding.simplifyingbusinesses.com',
    featured: true,
    order: 4,
  },
  {
    slug: 'calendar-hub',
    title: 'Calendar-Hub',
    tagline: 'Dual Outlook Scheduling for Client Appointments',
    description: 'A scheduling hub that connects the ALBS client onboarding portal to Microsoft Outlook calendars — enabling clients to self-book appointments that automatically populate both Franklin\'s and Nadesha\'s Outlook calendars simultaneously via Microsoft Graph API.',
    challenge: 'Scheduling client appointments required back-and-forth email coordination. The admin had to manually create calendar events in two separate Outlook accounts for each confirmed booking.',
    approach: 'Built a token-gated booking page that reads client availability preferences from the admin portal, generates client-specific time slots, and on submission performs a dual-write to two Office 365 accounts via Microsoft Graph API — with server-side Prisma database writes and immediate email confirmations to both client and admin.',
    solution: 'Clients receive a unique booking URL post-onboarding. They select a date and time from available slots. On confirmation: both Outlook calendars update simultaneously, the client gets a branded confirmation email, and Franklin receives an admin notification with full booking details and a prompt to set up Zoom and confirm with the client.',
    results: [
      'Dual Microsoft Graph calendar write — Franklin + Nadesha calendars updated simultaneously',
      'Past-date and double-booking filtering — slots always accurate',
      'Admin booking notification email with client details and Zoom setup CTA',
      'Client confirmation email with all appointment details',
      'BookingSlot Prisma model prevents double-booking at the database level',
      'Live at vercel-app-sooty-nu.vercel.app, integrated with onboarding.simplifyingbusinesses.com',
    ],
    tags: ['Microsoft Graph API', 'Next.js', 'TypeScript', 'Prisma', 'Resend', 'Vercel', 'Outlook', 'Office 365'],
    category: 'Internal',
    role: 'Sole Architect & Developer',
    timeline: 'April 2026',
    liveUrl: 'https://vercel-app-sooty-nu.vercel.app',
    featured: true,
    order: 5,
  },
  {
    slug: 'prospyr-dashboard',
    title: 'Prospyr Control Center',
    tagline: 'Multi-Agent Orchestration Dashboard',
    description: 'A web dashboard for managing and commanding autonomous AI agents (Prospyr, Northstar, Southstar, Zo) via SSE — built for Franklin\'s AI business operations infrastructure.',
    challenge: 'Managing multiple AI instances across different hosts (Oracle VPS, Northstar local, Office Paled server) required a unified control interface with real-time status and command delivery.',
    approach: 'Next.js + SSE architecture. Agents connect to the dashboard via Server-Sent Events, registering their capabilities and status. The dashboard pushes commands to specific agents and receives typed responses in real time.',
    solution: 'A live agent grid shows online/offline/working status per agent. A command center allows sending tasks with automatic routing to the right agent based on capabilities. Activity log captures every run with timestamps.',
    results: [
      'Live agent grid with real-time SSE status updates',
      'Task dispatch with agent capability routing',
      'Activity log with per-run details',
      'Deployed to Vercel, agents connect from anywhere',
    ],
    tags: ['Next.js', 'SSE', 'TypeScript', 'AI Agents', 'Vercel'],
    category: 'Internal',
    role: 'Sole Architect & Developer',
    timeline: 'March 2026',
    repoUrl: 'https://github.com/FranklinIV94/prospyr-dashboard',
    featured: true,
    order: 5,
  },
  {
    slug: 'kite-hackathon',
    title: 'Kite AI × Encode Club Hackathon',
    tagline: 'x402 Protocol + ERC-8004 Agent Identity on Base',
    description: 'An AI agent payment demo showcasing autonomous service transactions — agent registration via ERC-8004 identity registry and HTTP-native micropayments via x402 protocol on Base.',
    challenge: 'AI agents need to pay for services autonomously, but existing payment infrastructure requires human signatures, pre-funded accounts, and Web3 complexity. The agentic economy needs native payment primitives.',
    approach: 'Built a complete demo: Solidity contracts for agent identity and service payments, a Next.js dashboard for agent registration and service browsing, and a Python x402 server with agent client showing the full payment flow.',
    solution: 'Agent registers on-chain via ERC-8004 Identity Registry (0x8004...). Agent calls x402-protected endpoint → gets 402 Payment Required → signs EIP-3009 authorization → server verifies, settles on USDC, delivers data. Reputation recorded via ERC-8004 Reputation Registry.',
    results: [
      'ERC-8004 agent identity registration with cross-chain support (20+ chains)',
      'Full x402 payment flow — HTTP 402 → EIP-3009 → on-chain settlement',
      'AgentServiceGateway contract with service pricing in USDC',
      'Python x402 server with 5 service endpoints + agent client demo',
    ],
    tags: ['x402', 'ERC-8004', 'AI Agents', 'Base', 'Solidity', 'Python', 'Next.js', 'Hackathon'],
    category: 'Hackathon',
    role: 'Sole Architect & Developer',
    timeline: 'April 2026',
    liveUrl: 'https://github.com/FranklinIV94/kite-hackathon',
    repoUrl: 'https://github.com/FranklinIV94/kite-hackathon',
    featured: true,
    order: 7,
  },
  {
    slug: 'hackathon-2026',
    title: 'Encode Hackathon 2026',
    tagline: 'GenLayer × Base + InvoiceFi BNB Chain',
    description: 'Dual-track hackathon submission for Encode Club 2026 — Track 1: GenLayer intelligent contract with Web3.js frontend on Base. Track 2: InvoiceFi on BNB Chain with on-chain invoice financing.',
    challenge: 'Two separate tracks requiring different blockchain ecosystems and smart contract models. GenLayer offers LLM-backed intelligent contracts while BNB Chain provides established DeFi primitives.',
    approach: 'Track 1: Built an Intelligent Contract on GenLayer testnet with a React demo UI. Track 2: Developed an invoice financing dApp on BNB Chain with smart contract-based repayment logic.',
    solution: 'Two complete hackathon submissions demonstrating multi-chain capabilities — GenLayer for AI-augmented contracts and BNB Chain for DeFi-powered invoice financing. Both tracks include working code and deployed testnet contracts.',
    results: [
      'Track 1: GenLayer intelligent contract deployed on testnet',
      'Track 2: InvoiceFi smart contract on BNB Chain testnet',
      'React/Web3.js demo UIs for both tracks',
      'Published at github.com/FranklinIV94/hackathon-2026',
    ],
    tags: ['GenLayer', 'BNB Chain', 'Blockchain', 'Solidity', 'Web3.js', 'React', 'Hackathon'],
    category: 'Hackathon',
    role: 'Sole Architect & Developer',
    timeline: 'March 2026',
    repoUrl: 'https://github.com/FranklinIV94/hackathon-2026',
    featured: false,
    order: 8,
  },
  {
    slug: 'albs-tax-simplifier',
    title: 'ALBS Tax Simplifier',
    tagline: 'AI-Powered Tax Document Management for Businesses',
    description: 'A fully rebranded AI accounting platform built from Vas3k/TaxHacker — deployed for All Lines Business Solutions to deliver intelligent receipt scanning, expense categorization, transaction management, multi-currency support, invoice generation, and AI-driven data extraction entirely under the ALBS brand.',
    challenge: 'Business tax workflows are fragmented, error-prone, and expensive. Off-the-shelf accounting tools lack AI capabilities and lock businesses into proprietary ecosystems. ALBS needed a platform that could demonstrate AI-accelerated methodology while serving real client needs — without vendor lock-in or external branding.',
    approach: 'Took Vas3k/TaxHacker as a foundation, stripped all upstream branding, rewired the entire stack with ALBS branding, xAI/Grok integration, ALBS email/config, and a fresh deployment. Built as a completely standalone product with no dependency on the upstream project.',
    solution: 'ALBS Tax Simplifier is live at tax-simplifier.vercel.app — a private-label AI accounting platform with Grok-powered document scanning, transaction management, invoice generation, multi-currency support, and full data export. Fully owned by ALBS with zero upstream ties.',
    results: [
      'Live deployment at tax-simplifier.vercel.app — completely rebranded from Vas3k/TaxHacker',
      'xAI/Grok LLM integration for AI document scanning and intelligent data extraction',
      'PostgreSQL backend via Supabase with full transaction and category management',
      'Invoice generation with multi-language and VAT/GST support',
      'Multi-currency support with historical exchange rates for 170+ currencies',
      'Stripe integration for subscription billing',
      'Zero upstream dependencies — clean git history, full ALBS ownership',
    ],
    tags: ['Next.js 15', 'PostgreSQL', 'Supabase', 'Grok', 'xAI', 'Better Auth', 'Stripe', 'TypeScript'],
    category: 'Production',
    role: 'Sole Architect, Developer & Deployer',
    timeline: 'April 2026',
    liveUrl: 'https://tax-simplifier.vercel.app',
    repoUrl: 'https://github.com/FranklinIV94/ALBS-Tax-Simplifier',
    featured: true,
    order: 7,
  },
  {
    slug: 'agentpay-solana',
    title: 'AgentPay Solana',
    tagline: 'Mobile-First AI Agent Payment Governance on Solana',
    description: 'A mobile-native dashboard for humans to govern AI agent spending in real-time — built for the Solana Seeker phone at Consensus 2026. Agents request payments, humans approve or reject from their phone, with configurable spending limits and daily caps.',
    challenge: '$340M lost last year to runaway AI agent spending. Agents are becoming autonomous economic actors — they can think and act, but nobody controls the wallet. AI agents make API calls, execute trades, and spend money with zero oversight.',
    approach: 'Built a full-stack Solana dApp with an Anchor on-chain program (8 instructions deployed to devnet), a mobile-first React dashboard with DeepSeek AI generating real payment requests, and a direct Keypair wallet that bypasses the MWA Chrome limitation on the Seeker phone.',
    solution: 'Humans see every agent payment request on their phone in real-time. Approve, reject, or let spending limits auto-enforce. Every action is on-chain. The daily spend bar updates live. It\'s parental controls for AI.',
    results: [
      'Anchor program deployed to Solana devnet with 8 instructions',
      'DeepSeek AI generating real LLM payment requests every 10-15 seconds',
      'Mobile-first dashboard designed for Solana Seeker phone',
      'Daily spending limits with real-time tracking',
      'x402 cross-chain bridge to Base for agentic commerce',
      'Demo mode with simulated balance for reliable presentations',
      'Presented at Consensus 2026 — received positive feedback on mobile UX and on-chain governance model',
    ],
    tags: ['Solana', 'Anchor', 'DeepSeek', 'AI Agents', 'x402', 'Next.js', 'TypeScript', 'Hackathon'],
    category: 'Hackathon',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    liveUrl: 'https://agentpay-solana.vercel.app',
    repoUrl: 'https://github.com/FranklinIV94/agentpay-solana',
    featured: true,
    order: 9,
  },
  {
    slug: 'agent-studio',
    title: 'Agent Studio',
    tagline: 'AI Agents That Reason, Act, and Pay — Powered by AWS Bedrock + Coinbase',
    description: 'A full-stack AI agent pipeline for autonomous commerce at Consensus 2026 — Director parses intent, Quant analyzes markets, Risk validates compliance via AWS Bedrock Nova Pro, and Execution settles x402 payments on Base. Every step shows its reasoning. Every payment creates an on-chain audit trail.',
    challenge: 'AI agents can think, but they can\'t PAY. The x402 protocol closes this gap — agents request data, get HTTP 402 Payment Required, pay USDC on Base, and receive the data. But who evaluates whether a payment should happen? Who ensures compliance?',
    approach: 'Built a 4-stage AI pipeline (Director → Quant → Risk → Execution) with AWS Bedrock Nova Pro for real-time risk evaluation, Coinbase Smart Wallet on Base Sepolia for on-chain payments, and full AWS infrastructure via CDK — 4 Lambda functions, 3 DynamoDB tables, API Gateway with 11 endpoints, CloudWatch dashboards and alarms.',
    solution: 'The agent pipeline is fully transparent — every step shows its reasoning. Bedrock Nova Pro evaluates whether payments should be approved, rejected, or flagged. x402 payments settle on Base in under 2 seconds. Five FSI data services (market data, sanctions screening, credit bureau, fraud risk, FX rates) are gated by x402, creating immutable on-chain audit trails. Compliance by design.',
    results: [
      '62 CloudFormation resources deployed via AWS CDK in 90 seconds',
      'AWS Bedrock Nova Pro — real AI risk evaluation and service discovery',
      'API Gateway with 11 live endpoints (x402, bedrock, wallets, leaderboard)',
      '4 Lambda functions + 3 DynamoDB tables + CloudWatch dashboard with 6 widgets',
      'Coinbase Smart Wallet integration on Base Sepolia',
      '5 financial services data products gated by x402 protocol',
      'Presented at Consensus 2026 (Coinbase + AWS track) — demonstrated end-to-end AI agent commerce with on-chain settlement',
    ],
    tags: ['AWS', 'Bedrock', 'Coinbase', 'x402', 'Base', 'AI Agents', 'CDK', 'Lambda', 'DynamoDB', 'Hackathon'],
    category: 'Hackathon',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    liveUrl: 'https://agent-studio-fawn.vercel.app',
    repoUrl: 'https://github.com/FranklinIV94/agent-studio',
    featured: true,
    order: 10,
  },
  {
    slug: 'all-lines-claim-consultants',
    title: 'All Lines Claim Consultants',
    tagline: 'National Claims Management Platform & Lead Intelligence',
    description: 'A premium, animated marketing and lead capture platform for a national claims management firm. Built with Framer Motion animations, interactive service modals with detailed process breakdowns, an automated lead intelligence pipeline feeding into Supabase, and a secure admin dashboard with real-time lead management — all deployed live on a custom domain with Resend email notifications on every inquiry.',
    challenge: 'All Lines Claim Consultants needed a professional web presence that didn\'t just look good — it needed to actively generate and manage leads. The company handles workers\' compensation claims, drug testing, field investigations, and recorded statements across multiple states, but had no digital infrastructure to capture or manage client inquiries.',
    approach: 'Designed and built a Next.js 14 site with full Framer Motion animation system across 8 sections (hero with parallax and floating orbs, animated stat counters, staggered service cards, timeline process flow, testimonial cards, glass-morphism contact cards). Added clickable service modals showing detailed breakdowns with benefits and process steps. Built a lead capture form that feeds a dedicated Supabase backend with automated Resend email notifications to the business owner within seconds of submission.',
    solution: 'Every inquiry flows through a complete pipeline: form submission → Supabase persistence → Resend email notification to the business owner → admin dashboard for triage. The admin panel provides a real-time lead management interface with search, status filters (New → Contacted → Qualified → Closed), click-to-expand message details, inline status changes, and editable internal notes. Domain configured with Vercel DNS to bypass GoDaddy restrictions.',
    results: [
      'Live at alllinescc.com with SSL on custom Vercel DNS',
      'Automated lead pipeline: form → Supabase → Resend email notification',
      'Admin dashboard with search, status filtering, and inline lead management',
      '8 animated sections with Framer Motion — counters, staggers, parallax',
      '6 interactive service modals with detailed process breakdowns',
      'Session-password admin authentication with httpOnly secure cookies',
    ],
    tags: ['Next.js', 'Framer Motion', 'Supabase', 'Resend', 'Vercel', 'TypeScript', 'Tailwind'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    liveUrl: 'https://alllinescc.com',
    repoUrl: 'https://github.com/FranklinIV94/alcc-website',
    featured: true,
    order: 5,
  },
  {
    slug: 'workers-comp-automation-1',
    title: "Workers' Comp Automation",
    tagline: 'AI-Powered Wage Statement Automation with Human-in-the-Loop Verification',
    description: 'An AI-powered automation platform for workers\' compensation wage statements — replacing manual data entry with a 5-stage pipeline: Intake → AI Extraction → Normalization → HITL Review → State-Compliant PDF Generation. Covers 50-state DWC form mappings.',
    challenge: 'Workers\' comp wage statement preparation is labor-intensive, error-prone, and varies by state. Adjusters manually key data from pay stubs and employer statements into state-specific forms, with each state having different fields, calculation rules, and formatting requirements.',
    approach: 'Built a 5-stage pipeline: document intake and classification, AI extraction with structured output, normalization to standard schema, human-in-the-loop review with side-by-side verification UI, and state-compliant PDF generation from 50-state DWC form templates.',
    solution: 'Adjusters upload wage documents, the AI extracts and normalizes earnings data, a human reviewer verifies accuracy in a split-pane UI, and the system generates the correct state-specific DWC form PDF. Reduces per-statement processing from 20+ minutes to under 5 with verification.',
    results: [
      '5-stage pipeline: Intake → AI Extraction → Normalization → HITL Review → PDF',
      '50-state DWC form mapping with state-specific field requirements',
      'Human-in-the-loop verification — AI suggests, human confirms',
      'State-compliant PDF generation with employer and employee data pre-fill',
      'Built for All Lines Claims Consultants (ALCC)',
    ],
    tags: ['AI', 'Workers Comp', 'Insurance', 'PDF', 'TypeScript', 'Supabase'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    featured: false,
    order: 6,
  },
  {
    slug: 'training-platform-1',
    title: 'Training Platform',
    tagline: 'Modern LMS with Immersive Lesson Player for Professional Services',
    description: 'A modern learning management system with an immersive lesson player supporting text, quiz, video, and callout blocks — course builder, progress tracking, and Supabase backend. Built for professional services training at All Lines Business Solutions.',
    challenge: 'Professional services firms need training platforms that go beyond boring slide decks. Existing LMS options are either enterprise-priced or too rigid for custom lesson formats. ALBS needed a lightweight, modern LMS that could deliver engaging multi-format lessons without the enterprise overhead.',
    approach: 'Built a custom LMS with an immersive lesson player supporting multiple block types (text, quiz, video, callout), a drag-and-drop course builder, per-user progress tracking via Supabase, and a clean modern UI with Tailwind CSS.',
    solution: 'Courses are built from modular lesson blocks. Learners progress through immersive lesson pages with mixed content types. Progress is tracked per-user with resume capability. Deployed on Vercel with Supabase backend.',
    results: [
      'Immersive lesson player: text, quiz, video, and callout block types',
      'Drag-and-drop course builder for admin content creation',
      'Per-user progress tracking with resume capability',
      'Supabase backend with row-level security',
      'Deployed at albs-learning-center.vercel.app',
    ],
    tags: ['Next.js', 'Supabase', 'Vercel', 'LMS', 'Education', 'TypeScript', 'Tailwind'],
    category: 'Production',
    role: 'Sole Architect & Developer',
    timeline: 'May 2026',
    liveUrl: 'https://albs-learning-center.vercel.app',
    featured: false,
    order: 7,
  },
];

